language: python

python:
  - 3.5

before_install:
  - export DJANGO_SETTINGS_MODULE=travelperk_project.test.settings

install:
  - pip install -r requirements.txt

script:
  - python manage.py test

cache: pip