# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 01:09
from __future__ import unicode_literals

from django.db import migrations

import api.users.users_model


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.users.users_model.UserManager()),
            ],
        ),
    ]
