# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='from_place',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='to_place',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
